-- Supabase auth/profile/submitted data setup for SiamQuantum Atlas.
-- Apply this in the Supabase SQL editor or your Supabase migration workflow.

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  avatar_url text,
  bio text,
  website_url text,
  role text default 'user',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists submitted_data (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  title text not null,
  description text,
  source_url text,
  category text not null,
  page_target text,
  status text default 'pending',
  analysis_status text default 'queued',
  analysis_result jsonb,
  metadata jsonb default '{}'::jsonb,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text unique not null,
  slug text unique not null,
  description text,
  created_by uuid references auth.users(id),
  created_at timestamp with time zone default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on profiles;
create trigger set_profiles_updated_at
before update on profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_submitted_data_updated_at on submitted_data;
create trigger set_submitted_data_updated_at
before update on submitted_data
for each row execute function public.set_updated_at();

alter table profiles enable row level security;

create policy "Users can view their own profile"
on profiles
for select
to authenticated
using (auth.uid() = id);

create policy "Users can insert their own profile"
on profiles
for insert
to authenticated
with check (auth.uid() = id);

create policy "Users can update their own profile"
on profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "Admins can view all profiles"
on profiles
for select
to authenticated
using (
  exists (
    select 1
    from profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

alter table submitted_data enable row level security;

create policy "Users can insert their own submitted data"
on submitted_data
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can view their own submitted data"
on submitted_data
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can update their own pending submitted data"
on submitted_data
for update
to authenticated
using (
  auth.uid() = user_id
  and status = 'pending'
)
with check (
  auth.uid() = user_id
  and status = 'pending'
);

create policy "Users can delete their own pending submitted data"
on submitted_data
for delete
to authenticated
using (
  auth.uid() = user_id
  and status = 'pending'
);

create policy "Admins can manage all submitted data"
on submitted_data
for all
to authenticated
using (
  exists (
    select 1
    from profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);

create policy "Public can view approved submitted data"
on submitted_data
for select
to anon, authenticated
using (
  status = 'approved'
  and analysis_status = 'completed'
);

alter table categories enable row level security;

create policy "Anyone can view categories"
on categories
for select
to anon, authenticated
using (true);

create policy "Authenticated users can create categories"
on categories
for insert
to authenticated
with check (auth.uid() = created_by);

create policy "Admins can manage all categories"
on categories
for all
to authenticated
using (
  exists (
    select 1
    from profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from profiles p
    where p.id = auth.uid()
    and p.role = 'admin'
  )
);
